console.log(Math.abs(-4));
console.log(Math.round(4.2));
console.log(Math.ceil(4.2));
console.log(Math.floor(4.2));
console.log(Math.max(2,10,15,23));
console.log(Math.min(1,0,12,2));
console.log(Math.round(Math.random()*10));
const min=10;
const max=20;
console.log(Math.floor(Math.random()*(max-min+1))+min);